## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file EUThm-practice1.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (EUThm-practice1.sagetex.sage) was *autogenerated* from EUThm-practice1.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('EUThm-practice1', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()

