## -*- encoding: utf-8 -*-
## This file (numerical-Euler-practice1.sagetex.sage) was *autogenerated* from numerical-Euler-practice1.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('numerical-Euler-practice1', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
