## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file MAP2302UFO.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (MAP2302UFO.sagetex.sage) was *autogenerated* from MAP2302UFO.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('MAP2302UFO', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()

