## -*- encoding: utf-8 -*-
## This file (sec-vectors-maps.sagetex.sage) was *autogenerated* from sec-vectors-maps.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-vectors-maps', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
