## -*- encoding: utf-8 -*-
## This file (sec-advanced-linalg.sagetex.sage) was *autogenerated* from sec-advanced-linalg.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-advanced-linalg', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
