## -*- encoding: utf-8 -*-
## This file (sec-matrix-algebra.sagetex.sage) was *autogenerated* from sec-matrix-algebra.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-matrix-algebra', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
