## -*- encoding: utf-8 -*-
## This file (sec-determinant.sagetex.sage) was *autogenerated* from sec-determinant.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-determinant', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
