## -*- encoding: utf-8 -*-
## This file (first-existence.sagetex.sage) was *autogenerated* from first-existence.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('first-existence', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
