## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file first-order-lin.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (first-order-lin.sagetex.sage) was *autogenerated* from first-order-lin.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('first-order-lin', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()

