## -*- encoding: utf-8 -*-
## This file (sec-chapFO-review.sagetex.sage) was *autogenerated* from sec-chapFO-review.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-chapFO-review', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
