## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file separable.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (separable.sagetex.sage) was *autogenerated* from separable.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('separable', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()

