## -*- encoding: utf-8 -*-
## This file (sec-forced-oscillations.sagetex.sage) was *autogenerated* from sec-forced-oscillations.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-forced-oscillations', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
