## -*- encoding: utf-8 -*-
## This file (sec-higher-order-ode.sagetex.sage) was *autogenerated* from sec-higher-order-ode.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-higher-order-ode', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
