## -*- encoding: utf-8 -*-
## This file (sec-mechanical-vibrations.sagetex.sage) was *autogenerated* from sec-mechanical-vibrations.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-mechanical-vibrations', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
