## -*- encoding: utf-8 -*-
## This file (sec-second-order-repeated.sagetex.sage) was *autogenerated* from sec-second-order-repeated.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('sec-second-order-repeated', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
